const config=window.LILITH_CONFIG||{};const configured=Boolean(config.supabaseUrl&&config.supabaseAnonKey);const sb=configured?window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey):null;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let mode="login",motionEnabled=!matchMedia("(prefers-reduced-motion: reduce)").matches;
function showView(id){$$('.view').forEach(v=>{v.classList.remove('is-active');v.setAttribute('aria-hidden','true')});const view=$(id);view.classList.add('is-active');view.setAttribute('aria-hidden','false')}
function setMode(next){mode=next;$$('.auth-tab').forEach(t=>{const active=t.dataset.mode===next;t.classList.toggle('is-active',active);t.setAttribute('aria-selected',String(active))});$('#submit-label').textContent=next==='login'?'踏入镜中':'缔结契约';$('#password-label').textContent=next==='login'?'密码':'创建密码';$('#password').autocomplete=next==='login'?'current-password':'new-password';$('#reset-password').hidden=next!=='login';$('#auth-status').textContent=''}
$$('.auth-tab').forEach(t=>t.addEventListener('click',()=>setMode(t.dataset.mode)));$('#toggle-password').addEventListener('click',()=>{const input=$('#password');input.type=input.type==='password'?'text':'password';$('#toggle-password i').className=input.type==='password'?'ph ph-eye':'ph ph-eye-slash'});
async function enterArchive(user){$('#visitor-email').textContent=user?.email||'Mirror bond · stable';showView('#transition-view');if(motionEnabled){const tl=gsap.timeline({onComplete:()=>{showView('#archive-view');animateArchive()}});tl.fromTo('.mirror-rings span',{scale:.35,autoAlpha:0},{scale:1,autoAlpha:1,duration:1.15,stagger:.12,ease:'power3.out'}).from('.fractures',{autoAlpha:0,scale:.5,duration:.8,ease:'power2.out'},'<.15').from('.transition-copy>*',{y:22,autoAlpha:0,stagger:.08,duration:.55},'<.2').to('.transition-view',{autoAlpha:0,duration:.45,delay:.5})}else{setTimeout(()=>{showView('#archive-view');animateArchive()},400)}}
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value.trim(),password=$('#password').value,status=$('#auth-status');if(!email||password.length<8){status.textContent='请输入有效邮箱与至少 8 位密码。';return}if(!configured){status.textContent='Supabase 尚未配置。';return}status.textContent='镜面正在确认你的身份…';const result=mode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});if(result.error){status.textContent=result.error.message;return}if(mode==='signup'&&!result.data.session){status.textContent='确认邮件已经送达，请验证邮箱后再登录。';return}enterArchive(result.data.user)});
$('#reset-password').addEventListener('click',async()=>{const email=$('#email').value.trim(),status=$('#auth-status');if(!configured){status.textContent='Supabase 尚未配置。';return}if(!email){status.textContent='请先输入邮箱。';return}const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin});status.textContent=error?error.message:'重置邮件已经送达。'});$('#sign-out').addEventListener('click',async()=>{if(sb)await sb.auth.signOut();showView('#auth-view');animateAuth()});
$('#archive-nav').addEventListener('click',e=>{const btn=e.target.closest('.nav-item');if(!btn)return;$$('.nav-item').forEach(n=>n.classList.toggle('is-active',n===btn));$$('.section-panel').forEach(p=>p.classList.toggle('is-active',p.dataset.panel===btn.dataset.section));if(motionEnabled)gsap.from(`.section-panel[data-panel="${btn.dataset.section}"]>*`,{y:18,autoAlpha:0,stagger:.06,duration:.5,ease:'power2.out'})});
$('#motion-toggle').addEventListener('click',()=>{motionEnabled=!motionEnabled;$('#motion-toggle').classList.toggle('is-off',!motionEnabled);if(!motionEnabled)gsap.globalTimeline.pause();else gsap.globalTimeline.resume()});$('#sound-toggle').addEventListener('click',()=>$('#sound-toggle i').className=$('#sound-toggle i').classList.contains('ph-speaker-high')?'ph ph-speaker-slash':'ph ph-speaker-high');
function animateAuth(){if(!motionEnabled)return;gsap.fromTo('.auth-panel',{x:80,autoAlpha:0},{x:0,autoAlpha:1,duration:1,ease:'power3.out'});gsap.from('.brand-lockup>*',{y:20,autoAlpha:0,stagger:.08,duration:.7,delay:.25});gsap.to('.character-image',{scale:1.018,duration:4.8,yoyo:true,repeat:-1,ease:'sine.inOut'});gsap.to('.character-breath',{scale:1.08,autoAlpha:.7,duration:3.6,yoyo:true,repeat:-1,ease:'sine.inOut'});gsap.to('.eye-glow',{autoAlpha:.9,duration:2.2,yoyo:true,repeat:-1,ease:'sine.inOut'})}
function animateArchive(){if(!motionEnabled)return;gsap.from('.archive-content>*',{y:20,autoAlpha:0,stagger:.06,duration:.65,ease:'power2.out'});gsap.from('.nav-item',{x:-18,autoAlpha:0,stagger:.05,duration:.55});gsap.to('.archive-backdrop img',{scale:1.025,duration:6,yoyo:true,repeat:-1,ease:'sine.inOut'})}
function setupCursor(){const stage=$('#character-stage');addEventListener('pointermove',e=>{if(!motionEnabled)return;const x=e.clientX/innerWidth-.5,y=e.clientY/innerHeight-.5;gsap.to('.eye-glow',{x:x*12,y:y*7,duration:.35,overwrite:'auto'});gsap.to('.character-image',{x:x*-8,y:y*-5,duration:1.1,ease:'power2.out',overwrite:'auto'});if(stage)stage.style.setProperty('--cursor-x',`${e.clientX}px`)})}
function setupParticles(){const canvas=$('#presence-canvas'),ctx=canvas.getContext('2d'),particles=Array.from({length:38},()=>({x:Math.random(),y:Math.random(),r:.5+Math.random()*1.6,s:.00015+Math.random()*.0003,a:.12+Math.random()*.35}));function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(motionEnabled){for(const p of particles){p.y-=p.s;if(p.y<0)p.y=1;ctx.beginPath();ctx.fillStyle=`rgba(220,52,93,${p.a})`;ctx.arc(p.x*canvas.width,p.y*canvas.height,p.r*devicePixelRatio,0,Math.PI*2);ctx.fill()}}requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw()}
async function boot(){if(!configured)$('#config-warning').hidden=false;setupCursor();setupParticles();const localPreview=['127.0.0.1','localhost'].includes(location.hostname)&&new URLSearchParams(location.search).get('preview')==='archive';if(localPreview){showView('#archive-view');animateArchive();return}animateAuth();if(sb){const {data}=await sb.auth.getSession();if(data.session)enterArchive(data.session.user)}}
boot();
